import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DropNavbar from "@/components/Navbar/DropNavbar";
import ReduxProvider from "@/lib/ReduxProvider";
import ThemeRegistry from "@/theme/themeRegistry";
import AuthLoader from "@/lib/AuthLoader";
import SessionProvider from "@/lib/SessionProvider";
import Providers from "@/lib/Providers";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#F2F2F2] relative min-h-screen max-w-[100vw] overflow-x-hidden`}
      >
        <SessionProvider session={session}>
        <Providers>
          <DropNavbar />
          <div>{children}</div>
          </Providers>
          </SessionProvider>
      </body>
    </html>
  );
}
